[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "FQZx4j3m7Ee62heHrubVmNeNzQ7KT8FfirjiufrXYtQa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/john/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
